accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/' , views.UserRegisterView.as_view() , name = 'user_register'),
    path('verify/' , views.UserRegisterVerifyCodeView.as_view() , name = 'verify_code'),

]

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj/<str:key>/', views.DeleteBucketObject.as_view(), name='delete_obj'),
]
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/' , include('accounts.urls' , namespace='accounts'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .managers import UserManager
""" create base user """


class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=11, unique=True)
    full_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    """ import user manager """
    objects = UserManager()

    """ login user field """
    USERNAME_FIELD = 'phone_number'

    """ request field when create superuser """
    REQUIRED_FIELDS = ['email', 'full_name']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

class OtpCode(models.Model):
    phone_number = models.CharField(max_length=11)
    code = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.phone_number} - {self.code} - {self.created}'

home/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200 , unique=True)

    class Meta:
        ordering = ('name' , )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category , on_delete=models.CASCADE , related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200 , unique=True)
    image = models.ImageField()
    description = models.TextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name' , )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:product_detail' , args=[self.slug,])

accounts/forms.py
from django import forms
from .models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'phone_number', 'full_name')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('passwords dont match')
        return cd['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        help_text="you can change password using <a href=\"../password/\">this form</a>.")

    class Meta:
        model = User
        fields = ('email', 'phone_number', 'full_name', 'password', 'last_login')

class UserRegistrationForm(forms.Form):
    email = forms.EmailField()
    full_name = forms.CharField(label='Full name')
    phone = forms.CharField(max_length=11)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email = email).exists()
        if user:
            raise ValidationError('this email already exist')
        return user

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        user = User.objects.filter(phone_number = phone).exists()
        if user:
            raise ValidationError('this phone number already exist')
        return user


class VerifyCodeForm(forms.Form):
    code = forms.IntegerField()

accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm, VerifyCodeForm
from django.views import View
import random
from utils import send_otp_code
from .models import OtpCode, User
from django.contrib import messages


class UserRegisterView(View):
    form_class = UserRegistrationForm
    template_name = 'accounts/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            random_code = random.randint(10000, 99999)
            send_otp_code(form.cleaned_data['phone'], random_code)

            OtpCode.objects.create(phone_number=form.cleaned_data['phone'], code=random_code)
            request.session['user_register_info'] = {
                'phone_number': form.cleaned_data['phone'],
                'email': form.cleaned_data['email'],
                'full_name': form.cleaned_data['full_name'],
                'password': form.cleaned_data['password'],
            }
            messages.success(request, 'we sent you a code', 'success')
            return redirect('accounts:verify_code')
        return render(request, self.template_name, {'form': form})


class UserRegisterVerifyCodeView(View):
    form_class = VerifyCodeForm

    def get(self, request):
        form = self.form_class
        return render(request, 'accounts/verify.html', {'form': form})

    def post(self, request):
        user_session = request.session['user_register_info']
        code_instance = OtpCode.objects.get(phone_number=user_session['phone_number'])
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code:
                User.objects.create_user(user_session['phone_number'], user_session['email'], user_session['full_name'],
                                         user_session['password'])
                code_instance.delete()
                messages.success(request, 'you registered.', 'success')
                return redirect('home:home')
            else:
                messages.error(request, 'this code is wrong', 'danger')
                return redirect('accounts:verify_code')
        return redirect('home:home')

home/views.py
from django.shortcuts import render, get_object_or_404 , redirect
from django.views import View
from .models import Product
from . import tasks
from django.contrib import messages


class HomeView(View):
    def get(self, request):
        products = Product.objects.filter(available=True)
        return render(request, 'home/home.html', {'products': products})


class ProductDetailView(View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        return render(request, 'home/detail.html', {'product': product})


class BucketHome(View):
    template_name = 'home/bucket.html'

    def get(self , request):
        objects = tasks.all_bucket_objects_task()
        return render(request , self.template_name , {'objects':objects})


class DeleteBucketObject(View):
    def get(self , request , key):
        tasks.delete_object_task.delay(key)
        messages.success(request , 'your object will be delete soon' , 'info')
        return redirect('home:bucket')

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">


</form>

{% endblock %}

accounts/templates/accounts/verify.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">


</form>

{% endblock %}

home/templates/home/bucket.html
{% extends 'base.html' %}

{% block content %}

    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Size</th>
            <th scope="col">Download</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in objects %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ obj.Key }}</td>
            <td>{{ obj.Size|filesizeformat }}</td>
            <td>download</td>
        <td><a href="{% url 'home:delete_obj' obj.Key %}">delete</a></td>        </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}


{% block content %}
    <h2>{{ product.name }}</h2>
    <small>{{ product.created }}</small>
    <p>{{ product.price }} tooman</p>
    <img src="{{ product.image.url }}" alt="">
    <p>{{ product.description }}</p>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block extra_headers %}
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}

{% block content %}
<h3>Hello User</h3>
{% for product in products %}
<div class="card" style="width: 18rem; display:inline-block;">
    <img src="{{ product.image.url }}" class="card-img-top">
    <div class="card-body">
        <a href="{{ product.get_absolute_url }}" class="card-title">{{ product.name }}</a>
    </div>
</div>

{% endfor %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Shop</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}}">
    {% block extra_headers %}{% endblock %}
</head>
<body>

    {% include 'inc/navbar.html' %}
    <div class="jumbotron">
        {% include 'inc/messages.html' %}
        {% block content %} {% endblock %}
    </div>

</body>
</html>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
            <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
            {% if request.user.is_admin %}
            <a class="nav-link active" href="{% url 'home:bucket' %}">Bucket</a>
            {% endif %}
        </div>
    </div>
</nav> <br>